application: bunnytrivia
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /data
  static_dir: data
  application_readable: true
- url: /images
  static_dir: images
- url: /(robots\.txt|favicon\.ico|apple-touch-icon.*\.png|mstile-*\.png|crossdomain\.xml|humans\.txt)
  static_files: static/\1
  upload: static/(.*)
- url: /.*
  script: main.app
libraries:
- name: django
  version: "1.5"
- name: webapp2
  version: "2.5.2"
